name: Deploy Railway

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --ci --detach --project 32fe8394-03e2-42e5-bccc-95004caa95c7 --environment d262ffe2-46c8-4146-b9ca-b7410f0b1afc --service 28c71e0c-6ae0-444b-a3c0-a4e8e4fcaac1 --message "GitHub Actions deploy $GITHUB_SHA"
